### PR TITLE
Add `.gitignore`

### PR DESCRIPTION
**Pull request by ZanSara**
Just for convenience and prevent contributors from committing unnecessary files, let's add a `.gitignore` :slightly_smiling_face: This one is a fairly default template for Python projects.

### CODE REVIEW

**Comment by Mandera** [comment]
Looks good but I made an issue to generate this through generalpackager

**Comment by ZanSara** [comment]
No problem :) Can you tell me how do I get the `.gitignore` in my local development environment? The linked issue doesn't really help...

**Comment by Mandera** [comment]
Ah sorry, I didn't consider that I could merge this as a temporary solution. Also didn't know that it cannot be reopened when you deleted the branch, I'm learning so much!

If you reopen this I'll accept it! [The commit](https://github.com/ManderaGeneral/generalimport/pull/21/commits/f9fb19fd8f09dbf042e58eb1c642562fa57a2185) is still here though, that's interesting

**Comment by ZanSara** [comment]
I could restore the branch but not re-open the PR :sweat_smile: I'll try to open a new one from the same branch.

**Pull request closed without merging**
